### ISSUE TITLE
Implement a validation on the booking creation.

### ISSUE THREAD

**Issue by rubbuemen** [gii-is-psg2/PSG2-1819-G2-23#21]
Implement a validation on the booking creation of your pet hotel functionality that ensures that there are not concurrent bookings in the hotel for the same pet.

**Comment by LH97Ivan** [comment]
He tenido problemas a la hora de saber done implementar la restricción, ya que creía que lo tenía que hacer en los servicios, pero lo he hecho en el controlador de Hotel. Luego no sabía como implementarlo, hasta que me he acordado que podía usar binding.rejectValue dentro de un if para que me rechace un valor si se da cierta condición. No esta completo, me falta comprobar todas las fechas de reservas, para ver si la fecha que se mete en el formulario esta dentro de una de esas fechas.
